---
- name: Start oracle_db_exporter
  docker_container:
    name: oracle_db_exporter
    image: eams-repository.fltechnics.com/flt_oracle_db_exporter:latest
    networks:
      - name: fltechnics
    published_ports:
      - "9171:9161"
    restart_policy: always
    env:
      DATA_SOURCE_NAME: '{{ oracledb_live_username }}/{{ oracledb_live_password }}@//{{ oracledb_live_ip}}/{{ oracledb_live_dbname}}'
