---
- name: Start oracle_db_exporter_sensus_v2_uat
  docker_container:
    name: oracle_db_exporter_sensus_v2_uat
    image: eams-repository.fltechnics.com/flt_oracle_db_exporter:latest
    networks:
      - name: fltechnics
    published_ports:
      - "9174:9161"
    restart_policy: always
    env:
      DATA_SOURCE_NAME: '{{ oracledb_sensus_v2_uat_username }}/{{ oracledb_sensus_v2_uat_password }}@//{{ oracledb_sensus_v2_uat_ip}}/{{ oracledb_sensus_v2_uat_dbname}}'
