---

- name: Start oracle_db_exporter_mro_dev
  docker_container:
    name: oracle_db_exporter_mro_dev
    image: eams-repository.fltechnics.com/flt_oracle_db_exporter:latest
    networks:
      - name: fltechnics
    published_ports:
      - "9179:9161"
    restart_policy: always
    env:
      DATA_SOURCE_NAME: '{{ oracledb_mro_dev_username }}/{{ oracledb_mro_dev_password }}@//{{ oracledb_mro_dev_ip}}/{{ oracledb_mro_dev_dbname}}'
